include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    constant_identifier_names: ignore
    no_wildcard_variable_uses: ignore
    use_super_parameters: ignore
    avoid_print: ignore

linter:
  rules:
    # Preference of the SDK
    prefer_single_quotes: true
    prefer_final_locals: true
    unnecessary_brace_in_string_interps: false
    avoid_print: true

    # Enforce this for correct async logic
    unawaited_futures: true
    discarded_futures: true

formatter:
  page_width: 120
  trailing_commas: preserve
